kind = "web"
previewPath = "/"
title = "Anvesan"
version = "1.0.0"
id = "artifacts/anvesan"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19870

[services.development]
run = "pnpm --filter @workspace/anvesan run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/anvesan", "run", "build" ]
publicDir = "artifacts/anvesan/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19870"
BASE_PATH = "/"
